name: hugo-publish
on: 
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false
          path: ./source
      - run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_extended_0.111.3_linux-amd64.deb
          sudo dpkg -i hugo_extended_0.111.3_linux-amd64.deb
          hugo
          mv public $GITHUB_WORKSPACE/public
        working-directory: ./source
      - run: |
          git init
          git add --all
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "publish"
        working-directory: ./public
      - name: Push site
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: gh-pages
            force: true
            directory: ./public
        